/**
 * 로컬 개발용 목 데이터
 * .env.local에 USE_MOCK_DATA=true 설정 시 실제 Notion API 호출 대신 이 데이터를 반환
 */

export const isMock = () => process.env.USE_MOCK_DATA === "true";

// ─── HWDB ────────────────────────────────────────────────────
export const mockHwRecords = [
  {
    id: "mock-hw-1",
    notionUrl: "#",
    user: "홍길동",
    assetNo: "A-2024-001",
    model: "MacBook Pro 14",
    serial: "FVFMOCK001",
    maker: "Apple",
    cpu: "M3 Pro",
    ram: "18GB",
    company: "대웅제약",
    dept: "IT팀",
    location: "서울 본사 3층",
    status: "사용중",
    returnDue: "",
    returnDate: "",
    purchaseDate: "2024-01-15",
    useDate: "2024-02-01",
    price: 3500000,
    residualValue: 2800000,
    note: "",
    docNo: "IT-2024-001",
    verified: true,
    duplicated: false,
  },
  {
    id: "mock-hw-2",
    notionUrl: "#",
    user: "김철수",
    assetNo: "A-2024-002",
    model: "ThinkPad X1 Carbon",
    serial: "LNVMOCK002",
    maker: "Lenovo",
    cpu: "Intel i7-1365U",
    ram: "16GB",
    company: "대웅",
    dept: "개발팀",
    location: "수원 사무소",
    status: "사용중",
    returnDue: "2025-06-30",
    returnDate: "",
    purchaseDate: "2023-06-10",
    useDate: "2023-07-01",
    price: 2200000,
    residualValue: 1500000,
    note: "배터리 교체 필요",
    docNo: "IT-2023-042",
    verified: true,
    duplicated: false,
  },
  {
    id: "mock-hw-3",
    notionUrl: "#",
    user: "",
    assetNo: "A-2024-003",
    model: "Dell XPS 15",
    serial: "DELMOCK003",
    maker: "Dell",
    cpu: "Intel i9-13900H",
    ram: "32GB",
    company: "대웅제약",
    dept: "",
    location: "지하 창고",
    status: "재고",
    returnDue: "",
    returnDate: "",
    purchaseDate: "2022-11-20",
    useDate: "",
    price: 2900000,
    residualValue: 1800000,
    note: "",
    docNo: "",
    verified: false,
    duplicated: false,
  },
  {
    id: "mock-hw-4",
    notionUrl: "#",
    user: "이영희",
    assetNo: "A-2023-011",
    model: "Surface Pro 9",
    serial: "MSFMOCK004",
    maker: "Microsoft",
    cpu: "Intel i5-1245U",
    ram: "8GB",
    company: "대웅바이오",
    dept: "마케팅팀",
    location: "서울 본사 2층",
    status: "반납예정",
    returnDue: "2026-06-01",
    returnDate: "",
    purchaseDate: "2023-03-05",
    useDate: "2023-04-01",
    price: 1800000,
    residualValue: 900000,
    note: "",
    docNo: "IT-2023-011",
    verified: true,
    duplicated: false,
  },
  {
    id: "mock-hw-5",
    notionUrl: "#",
    user: "",
    assetNo: "A-2021-055",
    model: "LG gram 17",
    serial: "LGMOCK005",
    maker: "LG",
    cpu: "Intel i7-1165G7",
    ram: "16GB",
    company: "대웅제약",
    dept: "",
    location: "3층 문서고",
    status: "폐기",
    returnDue: "",
    returnDate: "2024-12-01",
    purchaseDate: "2021-05-10",
    useDate: "",
    price: 1600000,
    residualValue: 0,
    note: "액정 파손",
    docNo: "IT-2021-055",
    verified: false,
    duplicated: false,
  },
];

// ─── SW Item (화이트/블랙리스트) ─────────────────────────────
export const mockSwItems = [
  {
    id: "mock-sw-1",
    name: "Microsoft Office 365",
    vendor: "Microsoft",
    category: "오피스",
    status: "approved" as const,
    totalLicenses: 500,
    usedLicenses: 312,
    alternatives: [],
    mandatory: true,
    description: "사내 표준 오피스 솔루션",
    notionUrl: "#",
  },
  {
    id: "mock-sw-2",
    name: "Adobe Photoshop",
    vendor: "Adobe",
    category: "디자인",
    status: "conditional" as const,
    totalLicenses: 20,
    usedLicenses: 15,
    alternatives: ["GIMP", "Affinity Photo"],
    mandatory: false,
    description: "디자인팀 승인 후 사용 가능",
    notionUrl: "#",
  },
  {
    id: "mock-sw-3",
    name: "Zoom",
    vendor: "Zoom Video Communications",
    category: "협업",
    status: "approved" as const,
    totalLicenses: 999,
    usedLicenses: 0,
    alternatives: ["Teams"],
    mandatory: false,
    description: "화상 회의 도구",
    notionUrl: "#",
  },
  {
    id: "mock-sw-4",
    name: "BitTorrent",
    vendor: "BitTorrent Inc.",
    category: "기타",
    status: "banned" as const,
    totalLicenses: 0,
    usedLicenses: 0,
    alternatives: [],
    mandatory: false,
    description: "보안 정책에 의해 사용 금지",
    notionUrl: "#",
  },
];

// ─── SW Database (통합 DB) ────────────────────────────────────
export const mockSwDatabase = [
  {
    id: "mock-swdb-1",
    user: "홍길동",
    swCategory: "오피스",
    swDetail: "Microsoft 365 Business Standard",
    version: ["2024"],
    status: "사용중",
    company: "대웅제약",
    licenseType: "구독(업체)" as const,
    department: "IT팀",
    usageDate: "2024-01-01",
    renewalDate: "2025-01-01",
    purchaseDate: "2024-01-01",
    returnDate: "",
    shipStatus: "출고완료",
    accountType: "개인",
    renewalCycle: "연",
    licenseKey: "MOCK-KEY-001",
    vendor: "MS Korea",
    usageCount: 1,
    certificate: "",
    workType: "사무직",
    billingType: "법인카드",
    monthlyUsd: 12.5,
    monthlyKrw: 17000,
    annualUsd: 150,
    annualKrw: 204000,
    notionUrl: "#",
  },
  {
    id: "mock-swdb-2",
    user: "김철수",
    swCategory: "디자인",
    swDetail: "Adobe Creative Cloud All Apps",
    version: ["2024"],
    status: "사용중",
    company: "대웅",
    licenseType: "구독(업체)" as const,
    department: "마케팅팀",
    usageDate: "2023-06-01",
    renewalDate: "2024-06-01",
    purchaseDate: "2023-06-01",
    returnDate: "",
    shipStatus: "출고완료",
    accountType: "개인",
    renewalCycle: "연",
    licenseKey: "MOCK-ADOBE-002",
    vendor: "Adobe Korea",
    usageCount: 1,
    certificate: "",
    workType: "디자인",
    billingType: "법인카드",
    monthlyUsd: 54.99,
    monthlyKrw: 75000,
    annualUsd: 659.88,
    annualKrw: 900000,
    notionUrl: "#",
  },
];

// ─── Subscriptions ────────────────────────────────────────────
export const mockSubscriptions = [
  {
    id: "mock-sub-1",
    name: "GitHub Enterprise",
    logo: "🐙",
    version: "",
    status: "구독 중" as const,
    team: "개발팀",
    user: "개발팀 전체",
    userCount: 30,
    cycle: "월" as const,
    krw: 6600000,
    usd: undefined,
    paymentMethod: "법인카드",
    startDate: "2023-01-01",
    notionUrl: "#",
  },
  {
    id: "mock-sub-2",
    name: "Figma Organization",
    logo: "🎨",
    version: "",
    status: "구독 중" as const,
    team: "디자인팀",
    user: "이영희",
    userCount: 5,
    cycle: "연" as const,
    krw: undefined,
    usd: 900,
    paymentMethod: "법인카드",
    startDate: "2024-03-01",
    notionUrl: "#",
  },
];

// ─── Licenses ────────────────────────────────────────────────
export const mockLicenses = [
  {
    id: "mock-lic-1",
    name: "MS Office",
    category: "오피스",
    icon: "📄",
    usedCount: 150,
    totalCount: 200,
    expiryDate: "2026-12-31",
    status: "정상",
    notionUrl: "#",
  },
  {
    id: "mock-lic-2",
    name: "한컴",
    category: "오피스",
    icon: "🇰🇷",
    usedCount: 80,
    totalCount: 100,
    expiryDate: "2025-12-31",
    status: "정상",
    notionUrl: "#",
  },
  {
    id: "mock-lic-3",
    name: "Adobe Creative Cloud",
    category: "디자인",
    icon: "🎨",
    usedCount: 12,
    totalCount: 15,
    expiryDate: "2025-06-30",
    status: "정상",
    notionUrl: "#",
  },
];

// ─── License Records ──────────────────────────────────────────
export const mockLicenseRecords = [
  {
    id: "mock-lr-1",
    userName: "홍길동",
    software: "MS Office",
    softwareDetail: "Microsoft Office 2021 Pro",
    version: "2021",
    usageStatus: "사용중" as const,
    company: "대웅제약",
    department: "IT팀",
    email: "hong@example.com",
    licenseStartDate: "2024-01-01",
    licenseExpiryDate: "2026-12-31",
    usageStartDate: "2024-01-15",
    vendor: "MS Korea",
    serialNumber: "MOCK-SERIAL-001",
    notionUrl: "#",
  },
  {
    id: "mock-lr-2",
    userName: "이영희",
    software: "Adobe Creative Cloud",
    softwareDetail: "Adobe Creative Cloud All Apps",
    version: "2024",
    usageStatus: "사용중" as const,
    company: "대웅",
    department: "마케팅팀",
    email: "lee@example.com",
    licenseStartDate: "2023-06-01",
    licenseExpiryDate: "2024-06-01",
    usageStartDate: "2023-06-10",
    vendor: "Adobe Korea",
    serialNumber: "",
    notionUrl: "#",
  },
];

// ─── HelpDesk Tickets ─────────────────────────────────────────
export const mockHelpDeskTickets = [
  {
    id: "mock-hd-1",
    title: "노트북 화면 깜빡임 현상",
    status: "진행 중",
    inquiryType: "HW 장애",
    company: "대웅제약",
    department: "IT팀",
    requester: "홍길동",
    requesterEmail: "hong@example.com",
    assetNo: "A-2024-001",
    content: "노트북 화면이 간헐적으로 깜빡입니다.",
    urgency: "조금 급합니다.",
    team: "IT지원팀",
    assignee: "담당자A",
    assigneeId: "mock-user-1",
    submittedAt: "2026-05-10",
    lastEditedAt: "2026-05-11T09:00:00Z",
    notionUrl: "#",
    actionNote: "드라이버 업데이트 진행 중",
    actionCategory: ["HW 점검"],
    actionMethod: "원격 지원",
  },
  {
    id: "mock-hd-2",
    title: "VPN 연결 불가",
    status: "완료",
    inquiryType: "네트워크",
    company: "대웅",
    department: "개발팀",
    requester: "김철수",
    requesterEmail: "kim@example.com",
    assetNo: "",
    content: "재택 근무 중 VPN 연결이 되지 않습니다.",
    urgency: "매우 급합니다.",
    team: "IT지원팀",
    assignee: "담당자B",
    assigneeId: "mock-user-2",
    submittedAt: "2026-05-08",
    lastEditedAt: "2026-05-09T14:30:00Z",
    notionUrl: "#",
    actionNote: "인증서 재발급으로 해결",
    actionCategory: ["네트워크", "SW 설정"],
    actionMethod: "전화 지원",
  },
];

// ─── Tickets ──────────────────────────────────────────────────
export const mockTickets = [
  {
    id: "mock-tk-1",
    title: "신규 노트북 지급 요청",
    category: "HW 지급",
    priority: "중간" as const,
    status: "접수" as const,
    requester: "박지성",
    assignee: "담당자A",
    createdAt: "2026-05-11",
    description: "신입사원 입사로 노트북 지급 요청합니다.",
    notionUrl: "#",
  },
  {
    id: "mock-tk-2",
    title: "Adobe 라이선스 추가 요청",
    category: "SW 라이선스",
    priority: "낮음" as const,
    status: "처리중" as const,
    requester: "이영희",
    assignee: "담당자B",
    createdAt: "2026-05-09",
    description: "디자인팀 인원 증가로 Adobe CC 라이선스 2개 추가 필요",
    notionUrl: "#",
  },
];

// ─── Repair Tickets ───────────────────────────────────────────
export const mockRepairTickets = [
  {
    id: "mock-rt-1",
    ticketNumber: "RT-001",
    title: "키보드 일부 키 입력 불가",
    faultTypes: ["키보드 불량"],
    status: "진행 중" as const,
    priority: "조금 급합니다.",
    company: "대웅제약",
    department: "IT팀",
    location: "서울 본사 3층",
    assetId: "A-2024-001",
    requester: "홍길동",
    assignee: "담당자A",
    assigneeId: "mock-user-1",
    repairDate: "2026-05-15",
    actionNote: "키보드 모듈 교체 예정",
    consentGiven: true,
    createdAt: "2026-05-10",
    notionUrl: "#",
  },
];

// ─── HW Repair (외부 수리) ────────────────────────────────────
export const mockHwRepairs = [
  {
    id: "mock-hwr-1",
    assetId: "A-2024-002",
    company: "대웅",
    department: "개발팀",
    user: "김철수",
    vendor: "삼성서비스센터",
    stage: "수리중",
    receivedAt: "2026-05-05",
    completedAt: "",
    faultType: "과실아님",
    receiptUrl: [],
    consentUrl: [],
    taxInvoiceUrl: [],
    approvalUrl: [],
    assignee: "담당자A",
    assigneeId: "mock-user-1",
    note: "배터리 팽창으로 교체 의뢰",
    lastEditedAt: "2026-05-08T10:00:00Z",
    notionUrl: "#",
  },
];

// ─── Monitor History ──────────────────────────────────────────
export const mockMonitorHistory = [
  {
    id: "mock-mh-1",
    title: "Zone Move: 3층 회의실 A → 3층 회의실 B",
    itemId: "mock-item-1",
    label: "모니터 #001",
    building: "서울 본사",
    floor: "3F",
    eventType: "zone_move" as const,
    from: "3층 회의실 A",
    to: "3층 회의실 B",
    description: "회의실 리모델링으로 이동",
    status: "done" as const,
    createdAt: "2026-04-20",
    createdBy: "담당자A",
  },
];

// ─── Credentials (어드민 전용, 민감 정보 — 빈 배열로 반환) ────
export const mockCredentials: never[] = [];
