// 자동 생성 파일 — SW 설치 정책 화이트/블랙/예외 목록 확장 시드 데이터
// 생성: scripts 없이 1회성 변환 스크립트로 만들어졌습니다. 손으로 수정해도 되지만,
// 다음에 대량으로 다시 만들 경우 이 배열을 통째로 교체하는 편이 안전합니다.
import type { SwItem } from "@/types";

export type SwPolicySeedItem = Omit<SwItem, "id">;

export const SW_POLICY_SEED: SwPolicySeedItem[] = [
  {
    name: "LibreOffice",
    vendor: "The Document Foundation",
    category: "오피스",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "완전 무료 오픈소스 오피스 스위트(Writer/Calc/Impress). MPL 2.0 라이선스로 기업 무제한 사용 가능. MS Office 문서 호환.",
    officialUrl: "https://www.libreoffice.org",
  },
  {
    name: "ONLYOFFICE Community",
    vendor: "Ascensio System SIA",
    category: "오피스",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "오픈소스 오피스 편집기. MS Office 형식 완벽 호환. Community 버전 무료 사용 가능.",
    officialUrl: "https://www.onlyoffice.com",
  },
  {
    name: "Google Chrome",
    vendor: "Google LLC",
    category: "브라우저",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "기업 표준 브라우저. 무료 사용 가능. 기업 정책 관리(Google Workspace) 연동 지원.",
    officialUrl: "https://www.google.com/chrome",
  },
  {
    name: "Microsoft Edge",
    vendor: "Microsoft",
    category: "브라우저",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "Windows 기본 브라우저. Microsoft 365 연동 최적화. 기업 정책 관리 지원.",
    officialUrl: "https://www.microsoft.com/edge",
  },
  {
    name: "Visual Studio Code",
    vendor: "Microsoft",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 코드 편집기. MIT 라이선스. 기업 환경 무제한 사용 가능. 풍부한 확장 기능.",
    officialUrl: "https://code.visualstudio.com",
  },
  {
    name: "Git",
    vendor: "The Git Development Community",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "분산 버전 관리 시스템. GPL v2 라이선스. 기업 무제한 사용 가능. 소스코드 형상관리 필수 도구.",
    officialUrl: "https://git-scm.com",
  },
  {
    name: "Notepad++",
    vendor: "Don Ho",
    category: "개발도구",
    status: "approved",
    alternatives: ["Visual Studio Code"],
    mandatory: false,
    description: "경량 텍스트/코드 편집기. GPL v3 라이선스. 기업 무제한 사용 가능.",
    officialUrl: "https://notepad-plus-plus.org",
  },
  {
    name: "Python",
    vendor: "Python Software Foundation",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "범용 프로그래밍 언어. PSF 라이선스로 기업 무제한 사용 가능. 데이터 분석/자동화 업무에 활용.",
    officialUrl: "https://www.python.org",
  },
  {
    name: "Node.js",
    vendor: "OpenJS Foundation",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "JavaScript 런타임. MIT 라이선스. 기업 무제한 사용 가능.",
    officialUrl: "https://nodejs.org",
  },
  {
    name: "DBeaver Community",
    vendor: "DBeaver Corp.",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "오픈소스 데이터베이스 관리 도구. Apache 2.0 라이선스. MySQL, PostgreSQL, Oracle 등 지원.",
    officialUrl: "https://dbeaver.io",
  },
  {
    name: "7-Zip",
    vendor: "Igor Pavlov",
    category: "유틸리티",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 압축 프로그램. LGPL 라이선스. 기업 무제한 사용 가능. 높은 압축률, 암호화 지원.",
    officialUrl: "https://www.7-zip.org",
  },
  {
    name: "Bandizip (반디집)",
    vendor: "Bandisoft",
    category: "유틸리티",
    status: "approved",
    alternatives: ["7-Zip"],
    mandatory: false,
    description: "국산 무료 압축 프로그램. 개인/기업 모두 무료 사용 가능. 한글 파일명 완벽 지원.",
    officialUrl: "https://www.bandisoft.com",
  },
  {
    name: "VLC Media Player",
    vendor: "VideoLAN",
    category: "미디어",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 미디어 플레이어. GPL v2 라이선스. 기업 무제한 사용 가능. 모든 미디어 형식 지원.",
    officialUrl: "https://www.videolan.org",
  },
  {
    name: "Adobe Acrobat Reader",
    vendor: "Adobe Inc.",
    category: "뷰어",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 PDF 뷰어. Adobe 무료 사용 정책으로 기업 무제한 사용 가능. PDF 열람/출력/서명 지원.",
    officialUrl: "https://get.adobe.com/reader",
  },
  {
    name: "GIMP",
    vendor: "The GIMP Team",
    category: "디자인",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 이미지 편집 프로그램. GPL v3 라이선스. 기업 무제한 사용 가능. Photoshop 대안.",
    officialUrl: "https://www.gimp.org",
  },
  {
    name: "Inkscape",
    vendor: "Inkscape Project",
    category: "디자인",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 벡터 그래픽 편집기. GPL 라이선스. Illustrator 대안. SVG 편집 전문.",
    officialUrl: "https://inkscape.org",
  },
  {
    name: "WinSCP",
    vendor: "Martin Prikryl",
    category: "네트워크/보안",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 SFTP/FTP 클라이언트. GPL 라이선스. 서버 파일 전송에 사용.",
    officialUrl: "https://winscp.net",
  },
  {
    name: "PuTTY",
    vendor: "Simon Tatham",
    category: "네트워크/보안",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 SSH/텔넷 클라이언트. MIT 라이선스. 서버 원격 터미널 접속에 사용.",
    officialUrl: "https://www.putty.org",
  },
  {
    name: "Microsoft Teams",
    vendor: "Microsoft",
    category: "협업",
    status: "conditional",
    alternatives: [],
    mandatory: false,
    description: "사내 공식 협업 도구. Microsoft 365 라이선스 포함 시 사용 가능. 라이선스 담당자에게 확인 후 사용.",
    officialUrl: "https://www.microsoft.com/teams",
  },
  {
    name: "Zoom",
    vendor: "Zoom Video Communications",
    category: "협업",
    status: "conditional",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "화상회의 솔루션. 무료 버전 40분 제한. 기업용 라이선스 필요 시 IT 부서에 신청. 외부 거래처와의 회의 시 조건부 허용.",
    officialUrl: "https://zoom.us",
  },
  {
    name: "Slack",
    vendor: "Salesforce",
    category: "협업",
    status: "conditional",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "팀 메신저 플랫폼. 무료 버전 90일 메시지 제한. 기업 계약 여부 IT 부서 확인 필요.",
    officialUrl: "https://slack.com",
  },
  {
    name: "Postman",
    vendor: "Postman Inc.",
    category: "개발도구",
    status: "conditional",
    alternatives: [],
    mandatory: false,
    description: "API 테스트 및 개발 도구. 개인 계정 무료 사용 가능. 팀 기능은 유료. IT 부서 승인 후 사용.",
    officialUrl: "https://www.postman.com",
  },
  {
    name: "한/글 Viewer",
    vendor: "한글과컴퓨터",
    category: "오피스",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "HWP 문서 무료 뷰어(열람 전용, 편집 불가). 관공서·공공기관 문서 확인용.",
    officialUrl: "https://www.hancom.com",
  },
  {
    name: "Foxit PDF Reader",
    vendor: "Foxit Software",
    category: "뷰어",
    status: "approved",
    alternatives: ["Adobe Acrobat Reader"],
    mandatory: false,
    description: "무료 PDF 뷰어. Adobe Reader 대안, 가볍고 빠름.",
    officialUrl: "https://www.foxit.com",
  },
  {
    name: "SumatraPDF",
    vendor: "Krzysztof Kowalczyk",
    category: "뷰어",
    status: "approved",
    alternatives: ["Adobe Acrobat Reader"],
    mandatory: false,
    description: "초경량 오픈소스 PDF/전자책 뷰어. GPL 라이선스.",
    officialUrl: "https://www.sumatrapdfreader.org",
  },
  {
    name: "IntelliJ IDEA Community",
    vendor: "JetBrains",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 Java/Kotlin IDE. Apache 2.0 라이선스.",
    officialUrl: "https://www.jetbrains.com/idea",
  },
  {
    name: "PyCharm Community",
    vendor: "JetBrains",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 Python IDE. Apache 2.0 라이선스.",
    officialUrl: "https://www.jetbrains.com/pycharm",
  },
  {
    name: "Eclipse IDE",
    vendor: "Eclipse Foundation",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 통합개발환경. EPL 라이선스.",
    officialUrl: "https://www.eclipse.org",
  },
  {
    name: "GitHub Desktop",
    vendor: "GitHub, Inc.",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 Git GUI 클라이언트. MIT 라이선스.",
    officialUrl: "https://desktop.github.com",
  },
  {
    name: "Sourcetree",
    vendor: "Atlassian",
    category: "개발도구",
    status: "approved",
    alternatives: ["GitHub Desktop"],
    mandatory: false,
    description: "무료 Git GUI 클라이언트. 개인/소규모 팀 무료.",
    officialUrl: "https://www.sourcetreeapp.com",
  },
  {
    name: "MySQL Workbench",
    vendor: "Oracle",
    category: "개발도구",
    status: "approved",
    alternatives: ["DBeaver Community"],
    mandatory: false,
    description: "무료 MySQL 관리 도구. GPL 라이선스.",
    officialUrl: "https://www.mysql.com/products/workbench",
  },
  {
    name: "pgAdmin",
    vendor: "pgAdmin Development Team",
    category: "개발도구",
    status: "approved",
    alternatives: ["DBeaver Community"],
    mandatory: false,
    description: "무료 오픈소스 PostgreSQL 관리 도구.",
    officialUrl: "https://www.pgadmin.org",
  },
  {
    name: "Windows Terminal",
    vendor: "Microsoft",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "Windows 공식 터미널 앱. MIT 라이선스, Microsoft Store 무료 배포.",
    officialUrl: "https://aka.ms/terminal",
  },
  {
    name: ".NET SDK",
    vendor: "Microsoft",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: ".NET 애플리케이션 개발용 SDK. MIT 라이선스. 개발자가 직접 설치.",
    officialUrl: "https://dotnet.microsoft.com",
  },
  {
    name: "Insomnia",
    vendor: "Kong Inc.",
    category: "개발도구",
    status: "approved",
    alternatives: ["Postman"],
    mandatory: false,
    description: "API 테스트 도구. 무료 버전으로 충분히 사용 가능.",
    officialUrl: "https://insomnia.rest",
  },
  {
    name: "Docker Desktop",
    vendor: "Docker, Inc.",
    category: "개발도구",
    status: "conditional",
    alternatives: [],
    mandatory: false,
    description: "컨테이너 개발 도구. 소규모 기업(직원 250명 미만·매출 1000만불 미만)만 무료, 그 외 유료 라이선스 필요 — 조직 규모 기준 확인 후 사용.",
    officialUrl: "https://www.docker.com",
  },
  {
    name: "PowerToys",
    vendor: "Microsoft",
    category: "유틸리티",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "Windows 생산성 유틸리티 모음. MIT 라이선스 오픈소스.",
    officialUrl: "https://learn.microsoft.com/windows/powertoys",
  },
  {
    name: "PDF24 Creator",
    vendor: "Geek Software GmbH",
    category: "유틸리티",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 PDF 생성/편집 도구.",
    officialUrl: "https://www.pdf24.org",
  },
  {
    name: "TreeSize Free",
    vendor: "JAM Software",
    category: "유틸리티",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 디스크 사용량 분석 도구.",
    officialUrl: "https://www.jam-software.com/treesize_free",
  },
  {
    name: "WinDirStat",
    vendor: "WinDirStat 프로젝트",
    category: "유틸리티",
    status: "approved",
    alternatives: ["TreeSize Free"],
    mandatory: false,
    description: "오픈소스 디스크 사용량 시각화 도구.",
    officialUrl: "https://windirstat.net",
  },
  {
    name: "Rufus",
    vendor: "Pete Batard",
    category: "유틸리티",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 부팅 USB 제작 도구.",
    officialUrl: "https://rufus.ie",
  },
  {
    name: "balenaEtcher",
    vendor: "Balena",
    category: "유틸리티",
    status: "approved",
    alternatives: ["Rufus"],
    mandatory: false,
    description: "무료 오픈소스 OS 이미지 기록 도구.",
    officialUrl: "https://etcher.balena.io",
  },
  {
    name: "Everything",
    vendor: "voidtools",
    category: "유틸리티",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 초고속 파일 검색 도구(개인/기업 무료).",
    officialUrl: "https://www.voidtools.com",
  },
  {
    name: "ShareX",
    vendor: "ShareX Team",
    category: "유틸리티",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 스크린샷/화면녹화 도구. GPL 라이선스.",
    officialUrl: "https://getsharex.com",
  },
  {
    name: "Greenshot",
    vendor: "Greenshot 프로젝트",
    category: "유틸리티",
    status: "approved",
    alternatives: ["ShareX"],
    mandatory: false,
    description: "무료 오픈소스 스크린샷 도구.",
    officialUrl: "https://getgreenshot.org",
  },
  {
    name: "HandBrake",
    vendor: "HandBrake Team",
    category: "미디어",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 동영상 인코더. GPL 라이선스.",
    officialUrl: "https://handbrake.fr",
  },
  {
    name: "IrfanView",
    vendor: "Irfan Skiljan",
    category: "미디어",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 이미지 뷰어(개인/기업 사용 무료로 공식 명시).",
    officialUrl: "https://www.irfanview.com",
  },
  {
    name: "Blender",
    vendor: "Blender Foundation",
    category: "디자인",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 3D 제작 도구. GPL 라이선스.",
    officialUrl: "https://www.blender.org",
  },
  {
    name: "Krita",
    vendor: "Krita Foundation",
    category: "디자인",
    status: "approved",
    alternatives: ["GIMP"],
    mandatory: false,
    description: "무료 오픈소스 페인팅/일러스트 도구.",
    officialUrl: "https://krita.org",
  },
  {
    name: "FileZilla",
    vendor: "FileZilla Project",
    category: "네트워크/보안",
    status: "approved",
    alternatives: ["WinSCP"],
    mandatory: false,
    description: "무료 오픈소스 FTP/SFTP 클라이언트.",
    officialUrl: "https://filezilla-project.org",
  },
  {
    name: "Wireshark",
    vendor: "Wireshark Foundation",
    category: "네트워크/보안",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "무료 오픈소스 네트워크 패킷 분석 도구. IT/보안 담당자용.",
    officialUrl: "https://www.wireshark.org",
  },
  {
    name: "Notion",
    vendor: "Notion Labs",
    category: "협업",
    status: "conditional",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "문서·협업 도구. 개인/소규모 팀 무료, 조직 단위는 유료 플랜 필요 — IT 부서 확인 후 사용.",
    officialUrl: "https://www.notion.so",
  },
  {
    name: "Webex",
    vendor: "Cisco",
    category: "협업",
    status: "conditional",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "화상회의 솔루션. 무료 버전 시간 제한. 외부 거래처向 회의 시 조건부 허용.",
    officialUrl: "https://www.webex.com",
  },
  {
    name: "Miro",
    vendor: "Miro",
    category: "협업",
    status: "conditional",
    alternatives: [],
    mandatory: false,
    description: "온라인 화이트보드 협업 도구. 무료 플랜 보드 개수 제한.",
    officialUrl: "https://miro.com",
  },
  {
    name: "uTorrent (µTorrent)",
    vendor: "BitTorrent Inc.",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive", "SharePoint"],
    mandatory: false,
    description: "P2P 파일공유 프로그램. 저작권 침해 파일 유통 위험. 기업 보안정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "qBittorrent",
    vendor: "The qBittorrent Project",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive", "SharePoint"],
    mandatory: false,
    description: "오픈소스 P2P 파일공유 클라이언트. 기업 네트워크 보안 및 저작권 정책 위반으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "BitComet",
    vendor: "CometNetwork",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive"],
    mandatory: false,
    description: "BitTorrent/HTTP 복합 다운로드 프로그램. 기업 보안정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "eMule / 당나귀",
    vendor: "eMule Project",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "eD2k/Kad 네트워크 기반 P2P 프로그램. 기업 보안정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "RaiDrive (라이드라이브)",
    vendor: "OpenBoxLab",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive", "SharePoint"],
    mandatory: false,
    description: "NAS/클라우드 드라이브 마운트 도구. 외부 저장소 무단 연결 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Send Anywhere (센드애니웨어)",
    vendor: "Estmob Inc.",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive", "이메일"],
    mandatory: false,
    description: "P2P 파일 전송 앱. 기업 내부 데이터 외부 유출 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "카카오톡 (KakaoTalk)",
    vendor: "Kakao Corp.",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams", "사내 메신저"],
    mandatory: false,
    description: "개인용 모바일 메신저. 업무용 PC에서 사용 금지. 사내 공식 메신저(Microsoft Teams) 사용 권장.",
    officialUrl: undefined,
  },
  {
    name: "텔레그램 (Telegram)",
    vendor: "Telegram FZ-LLC",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "암호화 메신저 앱. 서버가 해외에 위치하여 기업 정보보안 정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Discord (디스코드)",
    vendor: "Discord Inc.",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "게임/커뮤니티용 음성·채팅 플랫폼. 기업 보안정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "LINE (라인)",
    vendor: "LINE Corp.",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "일본 기반 메신저 앱. 개인 정보 및 업무 데이터 유출 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "WeChat (위챗)",
    vendor: "Tencent",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "중국 기반 메신저. 데이터 보안 및 개인정보 보호법 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "WhatsApp",
    vendor: "Meta Platforms",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "개인용 메신저. 기업 내 업무 데이터 취급 금지.",
    officialUrl: undefined,
  },
  {
    name: "Skype (스카이프)",
    vendor: "Microsoft",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "개인용 화상통화/메신저. Microsoft Teams로 통합 대체. 개인용 Skype 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Signal (시그널)",
    vendor: "Signal Foundation",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "암호화 메신저. 기업 보안정책상 외부 메신저 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "네이트온 (NateOn)",
    vendor: "SK Communications",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "국내 개인용 메신저. 사내 공식 메신저 정책에 따라 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Mozilla Firefox",
    vendor: "Mozilla Foundation",
    category: "브라우저",
    status: "banned",
    alternatives: ["Google Chrome", "Microsoft Edge"],
    mandatory: false,
    description: "오픈소스 웹 브라우저. 기업 표준 브라우저(Chrome/Edge) 정책으로 사용 제한.",
    officialUrl: undefined,
  },
  {
    name: "Brave",
    vendor: "Brave Software",
    category: "브라우저",
    status: "banned",
    alternatives: ["Google Chrome", "Microsoft Edge"],
    mandatory: false,
    description: "광고 차단 내장 브라우저. 기업 표준 브라우저 정책으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Opera",
    vendor: "Opera Software",
    category: "브라우저",
    status: "banned",
    alternatives: ["Google Chrome", "Microsoft Edge"],
    mandatory: false,
    description: "중국 기업 소유 브라우저. 데이터 보안 정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "네이버 웨일 (Whale)",
    vendor: "Naver Corp.",
    category: "브라우저",
    status: "banned",
    alternatives: ["Google Chrome", "Microsoft Edge"],
    mandatory: false,
    description: "네이버 웨일 브라우저. 기업 표준 브라우저 정책으로 사용 제한.",
    officialUrl: undefined,
  },
  {
    name: "TeamViewer",
    vendor: "TeamViewer AG",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)", "사내 승인 원격접속 솔루션"],
    mandatory: false,
    description: "상용 원격접속 솔루션. 기업 환경에서 라이선스 비용 및 보안 위험으로 사용 금지. 승인된 원격접속 솔루션 사용 필수.",
    officialUrl: undefined,
  },
  {
    name: "AnyDesk",
    vendor: "AnyDesk Software GmbH",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)"],
    mandatory: false,
    description: "원격 데스크톱 소프트웨어. 기업 보안정책상 미승인 원격접속 도구 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Splashtop",
    vendor: "Splashtop Inc.",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)"],
    mandatory: false,
    description: "원격 접속/지원 솔루션. 미승인 원격접속 도구 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "RealVNC / TightVNC / UltraVNC",
    vendor: "VNC 계열",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)"],
    mandatory: false,
    description: "VNC 기반 원격접속 도구 전체. 기업 보안정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Dropbox",
    vendor: "Dropbox Inc.",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive", "SharePoint"],
    mandatory: false,
    description: "개인용 클라우드 스토리지. 기업 문서/데이터 외부 저장 금지. Microsoft OneDrive 사용 권장.",
    officialUrl: undefined,
  },
  {
    name: "MEGA (메가)",
    vendor: "Mega Limited",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive"],
    mandatory: false,
    description: "암호화 클라우드 스토리지. 기업 데이터 외부 저장 금지.",
    officialUrl: undefined,
  },
  {
    name: "TeraBox (테라박스)",
    vendor: "Flextech Inc.",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive"],
    mandatory: false,
    description: "중국 기반 클라우드 서비스. 데이터 보안 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "바이두 넷디스크 (Baidu Netdisk)",
    vendor: "Baidu Inc.",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive"],
    mandatory: false,
    description: "중국 바이두 클라우드 서비스. 기업 데이터 보안 및 개인정보 보호법 위반 위험.",
    officialUrl: undefined,
  },
  {
    name: "FrostWire",
    vendor: "FrostWire LLC",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive", "SharePoint"],
    mandatory: false,
    description: "P2P 파일공유 프로그램. 저작권 침해 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Vuze (Azureus)",
    vendor: "Vuze, Inc.",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive", "SharePoint"],
    mandatory: false,
    description: "토렌트 클라이언트. 기업 보안정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Deluge",
    vendor: "Deluge Team",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive", "SharePoint"],
    mandatory: false,
    description: "오픈소스 토렌트 클라이언트. 저작권·보안 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Transmission",
    vendor: "Transmission Project",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: ["OneDrive", "SharePoint"],
    mandatory: false,
    description: "토렌트 클라이언트. 기업 네트워크 보안정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Soulseek",
    vendor: "Soulseek Network",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "음원 P2P 공유 네트워크 클라이언트. 저작권 침해 위험.",
    officialUrl: undefined,
  },
  {
    name: "DC++",
    vendor: "DC++ 프로젝트",
    category: "P2P 파일공유",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "다이렉트 커넥트 기반 P2P 공유 프로그램. 저작권 침해 위험.",
    officialUrl: undefined,
  },
  {
    name: "QQ",
    vendor: "Tencent",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "중국 기반 메신저. 데이터 보안 및 개인정보 보호법 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Viber",
    vendor: "Rakuten Viber",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "개인용 모바일 메신저. 업무 데이터 취급 금지.",
    officialUrl: undefined,
  },
  {
    name: "밴드 (Band)",
    vendor: "Naver Corp.",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "개인/커뮤니티용 그룹 앱. 업무용 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Facebook Messenger",
    vendor: "Meta Platforms",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "개인용 메신저. 업무 데이터 취급 금지.",
    officialUrl: undefined,
  },
  {
    name: "Threema",
    vendor: "Threema GmbH",
    category: "메신저",
    status: "banned",
    alternatives: ["Microsoft Teams"],
    mandatory: false,
    description: "암호화 메신저. 외부 메신저 사용 금지 정책 위반.",
    officialUrl: undefined,
  },
  {
    name: "Tor Browser",
    vendor: "The Tor Project",
    category: "브라우저",
    status: "banned",
    alternatives: ["Google Chrome", "Microsoft Edge"],
    mandatory: false,
    description: "익명 네트워크 브라우저. 접속 추적 회피 및 보안 통제 우회 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "UC Browser",
    vendor: "Alibaba (UCWeb)",
    category: "브라우저",
    status: "banned",
    alternatives: ["Google Chrome", "Microsoft Edge"],
    mandatory: false,
    description: "중국 기반 브라우저. 데이터 보안 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Yandex Browser",
    vendor: "Yandex",
    category: "브라우저",
    status: "banned",
    alternatives: ["Google Chrome", "Microsoft Edge"],
    mandatory: false,
    description: "러시아 기반 브라우저. 데이터 보안 정책상 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Vivaldi",
    vendor: "Vivaldi Technologies",
    category: "브라우저",
    status: "banned",
    alternatives: ["Google Chrome", "Microsoft Edge"],
    mandatory: false,
    description: "기업 표준 브라우저 정책으로 사용 제한.",
    officialUrl: undefined,
  },
  {
    name: "Chrome Remote Desktop",
    vendor: "Google",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)"],
    mandatory: false,
    description: "개인용 원격 데스크톱 도구. 미승인 원격접속 경로로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Parsec",
    vendor: "Parsec Cloud, Inc.",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)"],
    mandatory: false,
    description: "게임/개인용 원격 스트리밍 도구. 업무 무관, 미승인 원격접속.",
    officialUrl: undefined,
  },
  {
    name: "LogMeIn",
    vendor: "GoTo",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)"],
    mandatory: false,
    description: "상용 원격접속 솔루션. 미승인 도구 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "ScreenConnect (ConnectWise Control)",
    vendor: "ConnectWise",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)"],
    mandatory: false,
    description: "원격 지원 솔루션. 미승인 시 사용 금지 — 사내 IT 지원은 승인된 경로만 사용.",
    officialUrl: undefined,
  },
  {
    name: "Radmin",
    vendor: "Famatech",
    category: "원격접속",
    status: "banned",
    alternatives: ["Windows 원격 데스크톱(RDP)"],
    mandatory: false,
    description: "원격관리 소프트웨어. 미승인 도구 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Google Drive (개인 계정)",
    vendor: "Google",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive", "SharePoint"],
    mandatory: false,
    description: "개인 Google 계정 기반 클라우드 동기화. 기업 문서 외부 저장 금지.",
    officialUrl: undefined,
  },
  {
    name: "pCloud",
    vendor: "pCloud AG",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive"],
    mandatory: false,
    description: "개인용 클라우드 스토리지. 기업 데이터 외부 저장 금지.",
    officialUrl: undefined,
  },
  {
    name: "Box (개인 계정)",
    vendor: "Box, Inc.",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive", "SharePoint"],
    mandatory: false,
    description: "미승인 개인 계정 사용 시 데이터 유출 위험. 회사 계약 없이 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "네이버 마이박스 (MYBOX)",
    vendor: "Naver Corp.",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive"],
    mandatory: false,
    description: "개인용 클라우드 스토리지. 기업 데이터 외부 저장 금지.",
    officialUrl: undefined,
  },
  {
    name: "iCloud Drive",
    vendor: "Apple Inc.",
    category: "외부 클라우드",
    status: "banned",
    alternatives: ["Microsoft OneDrive"],
    mandatory: false,
    description: "개인용 클라우드 동기화. 기업 데이터 외부 저장 금지.",
    officialUrl: undefined,
  },
  {
    name: "KMSpico",
    vendor: "비공식(배포자 불명)",
    category: "크랙/불법활성화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "Windows/Office 불법 라이선스 우회 도구. 저작권법 위반 및 악성코드 감염 위험 — 최우선 차단 대상.",
    officialUrl: undefined,
  },
  {
    name: "KMSAuto Net",
    vendor: "비공식(배포자 불명)",
    category: "크랙/불법활성화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "Microsoft 제품 불법 인증 우회 도구. 저작권법 위반, 보안 위험.",
    officialUrl: undefined,
  },
  {
    name: "Microsoft Toolkit",
    vendor: "비공식(배포자 불명)",
    category: "크랙/불법활성화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "Windows/Office 불법 활성화 도구. 저작권법 위반.",
    officialUrl: undefined,
  },
  {
    name: "Windows Loader (Daz)",
    vendor: "Daz",
    category: "크랙/불법활성화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "Windows 불법 활성화 도구. 저작권법 위반, 보안 위험.",
    officialUrl: undefined,
  },
  {
    name: "Re-Loader Activator",
    vendor: "비공식(배포자 불명)",
    category: "크랙/불법활성화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "Windows/Office 불법 활성화 도구. 저작권법 위반.",
    officialUrl: undefined,
  },
  {
    name: "HEU KMS Activator",
    vendor: "비공식(배포자 불명)",
    category: "크랙/불법활성화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "KMS 방식 불법 활성화 도구. 저작권법 위반.",
    officialUrl: undefined,
  },
  {
    name: "Adobe Zii",
    vendor: "비공식(배포자 불명)",
    category: "크랙/불법활성화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "Adobe 제품 불법 라이선스 우회 도구. 저작권법 위반.",
    officialUrl: undefined,
  },
  {
    name: "(패턴 규칙) crack/keygen/patch/activator/loader/serial 포함 실행파일",
    vendor: "-",
    category: "크랙/불법활성화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "정품 인증 우회 목적으로 추정되는 실행 파일 일반. 개별 등록이 아닌 이름 패턴 기반 자동 판정 규칙으로 반영 권장.",
    officialUrl: undefined,
  },
  {
    name: "NiceHash",
    vendor: "NiceHash",
    category: "채굴프로그램",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "암호화폐 채굴 소프트웨어. 회사 자원 무단 사용, 성능 저하 및 보안 위험.",
    officialUrl: undefined,
  },
  {
    name: "XMRig",
    vendor: "XMRig 프로젝트",
    category: "채굴프로그램",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "모네로 채굴 프로그램. 무단 설치 시 악성코드로 간주. 회사 자원 무단 사용.",
    officialUrl: undefined,
  },
  {
    name: "CGMiner / EasyMiner",
    vendor: "커뮤니티",
    category: "채굴프로그램",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "암호화폐 채굴 도구. 회사 PC 자원 무단 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "Steam",
    vendor: "Valve Corporation",
    category: "게임/런처",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "게임 플랫폼. 업무 PC 게임 설치 금지 정책 — 회사 최종 정책 확인 권장.",
    officialUrl: undefined,
  },
  {
    name: "Epic Games Launcher",
    vendor: "Epic Games",
    category: "게임/런처",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "게임 플랫폼. 업무 PC 게임 설치 금지 정책 — 회사 최종 정책 확인 권장.",
    officialUrl: undefined,
  },
  {
    name: "Battle.net",
    vendor: "Blizzard Entertainment",
    category: "게임/런처",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "게임 플랫폼. 업무 PC 게임 설치 금지 정책 — 회사 최종 정책 확인 권장.",
    officialUrl: undefined,
  },
  {
    name: "Riot Client",
    vendor: "Riot Games",
    category: "게임/런처",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "게임 플랫폼. 업무 PC 게임 설치 금지 정책 — 회사 최종 정책 확인 권장.",
    officialUrl: undefined,
  },
  {
    name: "개인 VPN 클라이언트 일반(ExpressVPN, NordVPN 등)",
    vendor: "각 벤더",
    category: "VPN/우회",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "개인용 VPN 서비스. 접속 통제 우회 및 데이터 유출 경로가 될 수 있어 미승인 사용 금지(회사 승인 VPN 있는 경우 제외).",
    officialUrl: undefined,
  },
  {
    name: "Psiphon",
    vendor: "Psiphon Inc.",
    category: "VPN/우회",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "검열/통제 우회 도구. 보안 통제 우회 위험으로 사용 금지.",
    officialUrl: undefined,
  },
  {
    name: "알집 (ALZip)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["7-Zip", "Bandizip"],
    mandatory: false,
    description: "압축 프로그램. 개인 사용은 무료이나 영리 목적(기업) 사용 시 유료 라이선스가 필요합니다. 무료판을 사내에서 계속 쓰면 라이선스 위반입니다.",
    officialUrl: undefined,
  },
  {
    name: "알약 (ALYac)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["사내 표준 백신"],
    mandatory: false,
    description: "백신 프로그램. 개인 무료, 기업 사용 시 알약 기업용 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "알PDF (ALPDF)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["Adobe Acrobat Reader", "Foxit PDF Reader"],
    mandatory: false,
    description: "PDF 편집 도구. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "알씨 (ALSee)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "이미지 뷰어. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "알송 (ALSong)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["VLC Media Player"],
    mandatory: false,
    description: "음악 재생 프로그램. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "알캡처 (ALCapture)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["ShareX", "Greenshot"],
    mandatory: false,
    description: "화면 캡처 도구. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "알FTP (ALFTP)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["WinSCP", "FileZilla"],
    mandatory: false,
    description: "FTP 클라이언트. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "알쇼 (ALShow)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["VLC Media Player"],
    mandatory: false,
    description: "동영상 재생 프로그램. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "알드라이브 (ALDrive)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["Microsoft OneDrive"],
    mandatory: false,
    description: "클라우드 드라이브 연동 도구. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다(외부 클라우드 반입 정책도 함께 검토 필요).",
    officialUrl: undefined,
  },
  {
    name: "알툴바 (ALToolbar)",
    vendor: "이스트소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "브라우저 툴바/유틸리티 모음. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "반디캠 (Bandicam)",
    vendor: "반디소프트",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "화면 녹화 프로그램. 개인 사용은 무료(워터마크·시간 제한)이나 기업 사용 시 상업용 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "곰플레이어 (GOM Player)",
    vendor: "그레텍",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["VLC Media Player"],
    mandatory: false,
    description: "동영상 재생 프로그램. 개인 무료, 영리 목적(기업) 사용 시 기업용 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "팟플레이어 (PotPlayer)",
    vendor: "카카오(다음)",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["VLC Media Player"],
    mandatory: false,
    description: "동영상 재생 프로그램. 개인용으로 배포되며 최근 약관에서 상업적 이용을 제한하고 있어 기업 사용 여부를 라이선스 조항으로 확인해야 합니다.",
    officialUrl: undefined,
  },
  {
    name: "V3 Lite",
    vendor: "AhnLab",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["사내 표준 백신"],
    mandatory: false,
    description: "개인용 무료 백신. 기업 사용 시 V3 for Business 등 유료 제품이 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "CCleaner",
    vendor: "Piriform (Gen Digital)",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "PC 최적화 도구. 개인 무료, 기업 사용 시 CCleaner Business/Cloud 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "WinRAR",
    vendor: "win.rar GmbH",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["7-Zip", "Bandizip"],
    mandatory: false,
    description: "압축 프로그램. 40일 평가판 이후 개인·기업 모두 유료가 원칙이나 무료로 오인해 계속 사용하는 사례가 많습니다.",
    officialUrl: undefined,
  },
  {
    name: "Advanced SystemCare",
    vendor: "IObit",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "PC 최적화 도구. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "Driver Booster",
    vendor: "IObit",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "드라이버 업데이트 도구. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "PicPick",
    vendor: "NGWIN",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: ["ShareX", "Greenshot"],
    mandatory: false,
    description: "스크린 캡처 도구. 개인 무료, 기업 사용 시 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "Recuva",
    vendor: "Piriform (Gen Digital)",
    category: "라이선스 오인(개인용 무료·기업 유료)",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "파일 복구 도구. 개인 무료, 기업 사용 시 Recuva Professional/Business 유료 라이선스가 필요합니다.",
    officialUrl: undefined,
  },
  {
    name: "AhnLab Safe Transaction",
    vendor: "AhnLab",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "은행/공공기관 접속 시 자동 설치되는 보안 프로그램. 사용자가 능동적으로 선택한 업무 도구가 아니므로 판정 대상에서 제외.",
    officialUrl: "https://www.ahnlab.com",
  },
  {
    name: "AhnLab V3",
    vendor: "AhnLab",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "백신 프로그램. 사내 표준 백신으로 지정된 경우 판정 대상에서 제외(별도 IT 정책으로 관리).",
    officialUrl: "https://www.ahnlab.com",
  },
  {
    name: "INISAFE 시리즈",
    vendor: "INITECH",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "공동인증서/전자서명 보안 모듈. 금융·공공 사이트 접속 시 자동 설치.",
    officialUrl: undefined,
  },
  {
    name: "TouchEn 시리즈",
    vendor: "RaonSecure",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "키보드 보안/인증 모듈. 은행·공공 사이트 접속 시 자동 설치.",
    officialUrl: undefined,
  },
  {
    name: "Veraport (베라포트)",
    vendor: "WIZVERA",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "보안 프로그램 통합 설치·관리 모듈. 공공·금융 사이트 표준 설치 프로그램.",
    officialUrl: undefined,
  },
  {
    name: "Delfino (델피노)",
    vendor: "WIZVERA",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "웹사이트 보안 통합 설치 관리자.",
    officialUrl: undefined,
  },
  {
    name: "MagicLine (매직라인)",
    vendor: "Dreamsecurity",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "공동인증서 기반 전자서명 모듈. 금융·공공 사이트 자동 설치.",
    officialUrl: undefined,
  },
  {
    name: "nProtect 시리즈",
    vendor: "INCA Internet",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "온라인 뱅킹/게임 보안 모듈.",
    officialUrl: undefined,
  },
  {
    name: "XecureWeb (시큐어웹)",
    vendor: "Softforum",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "전자서명/암호화 웹 보안 모듈.",
    officialUrl: undefined,
  },
  {
    name: "ISign+",
    vendor: "Penta Security",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "웹 보안/전자서명 통합 모듈.",
    officialUrl: undefined,
  },
  {
    name: "KSign 시리즈",
    vendor: "KSign",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "공동인증서 보안 모듈.",
    officialUrl: undefined,
  },
  {
    name: "Markany DRM 클라이언트",
    vendor: "Markany",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "문서 보안(DRM) 클라이언트. 사내 문서보안 정책 연동 시 자동 설치.",
    officialUrl: undefined,
  },
  {
    name: "Fasoo DRM 클라이언트",
    vendor: "Fasoo",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "문서 보안(DRM) 클라이언트.",
    officialUrl: undefined,
  },
  {
    name: "AnySign4PC",
    vendor: "한국정보인증 등",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "공동인증서 연동 서명 모듈. 금융·공공 사이트 자동 설치.",
    officialUrl: undefined,
  },
  {
    name: "IPinside / TrustGuard 계열",
    vendor: "각 벤더",
    category: "보안모듈",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "웹 보안·트래픽 통제 모듈. 사내 표준 보안 정책상 자동 설치되는 경우 판정 제외.",
    officialUrl: undefined,
  },
  {
    name: "Microsoft Visual C++ Redistributable(전 버전)",
    vendor: "Microsoft",
    category: "OS런타임",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "다수 프로그램이 의존하는 실행 라이브러리. 프로그램 설치 시 자동 동봉 설치.",
    officialUrl: undefined,
  },
  {
    name: "Microsoft .NET Runtime / Desktop Runtime",
    vendor: "Microsoft",
    category: "OS런타임",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: ".NET 기반 앱 실행에 필요한 런타임. 사용자가 직접 선택 설치하지 않는 경우가 대부분.",
    officialUrl: undefined,
  },
  {
    name: "DirectX Runtime",
    vendor: "Microsoft",
    category: "OS런타임",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "그래픽/멀티미디어 API 런타임. 다수 프로그램·게임에 필요해 자동 설치.",
    officialUrl: undefined,
  },
  {
    name: "Java Runtime Environment (JRE)",
    vendor: "Oracle",
    category: "OS런타임",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "웹사이트/업무 프로그램 실행에 필요한 자바 런타임. 사이트 요구로 자동 설치되는 경우가 많음(개발자가 능동 설치한 JDK는 개발도구로 별도 판정).",
    officialUrl: undefined,
  },
  {
    name: "WebView2 Runtime",
    vendor: "Microsoft",
    category: "OS런타임",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "Edge 기반 웹 콘텐츠 렌더링 런타임. 다수 앱이 내부적으로 사용, 자동 설치.",
    officialUrl: undefined,
  },
  {
    name: "Windows SDK 구성요소",
    vendor: "Microsoft",
    category: "OS런타임",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "개발 도구 설치 시 자동 동봉되는 SDK 구성요소.",
    officialUrl: undefined,
  },
  {
    name: "Intel Driver & Support Assistant",
    vendor: "Intel",
    category: "드라이버",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "인텔 칩셋/그래픽 드라이버 관리 도구.",
    officialUrl: undefined,
  },
  {
    name: "NVIDIA GeForce Experience / 드라이버",
    vendor: "NVIDIA",
    category: "드라이버",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "그래픽카드 드라이버 및 관리 도구.",
    officialUrl: undefined,
  },
  {
    name: "Realtek 오디오/이더넷 드라이버",
    vendor: "Realtek",
    category: "드라이버",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "메인보드 내장 오디오/랜 드라이버.",
    officialUrl: undefined,
  },
  {
    name: "AMD 그래픽/칩셋 드라이버",
    vendor: "AMD",
    category: "드라이버",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "AMD 하드웨어 드라이버.",
    officialUrl: undefined,
  },
  {
    name: "Synaptics 터치패드 드라이버",
    vendor: "Synaptics",
    category: "드라이버",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "노트북 터치패드 드라이버.",
    officialUrl: undefined,
  },
  {
    name: "HP/Dell/Lenovo 지원 유틸리티",
    vendor: "각 제조사",
    category: "드라이버",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "PC 제조사 번들 지원·업데이트 프로그램.",
    officialUrl: undefined,
  },
  {
    name: "프린터/스캐너 유틸리티(HP Smart 등)",
    vendor: "HP, Canon, Epson 등",
    category: "드라이버",
    status: "excluded",
    alternatives: [],
    mandatory: false,
    description: "프린터·스캐너 제조사 번들 소프트웨어.",
    officialUrl: undefined,
  },
];
