/**
 * 발표용 포털 데이터 시드 스크립트
 * node scripts/seed-portal.mjs
 */
import Redis from "ioredis";

const REDIS_URL = "redis://default:A7dsOsfhH4f5tcusiFGSFsU5FdNuES2y@redis-14310.crce220.us-east-1-4.ec2.cloud.redislabs.com:14310";

const now = new Date().toISOString();
const today = now.slice(0, 10);

// ─── 교육센터 (Courses) ──────────────────────────────────────────────────────
const COURSES = [
  {
    id: "c_edu_001",
    title: "소프트웨어 라이선스의 종류와 이해",
    description: "개인·법인·범용·오픈소스 라이선스의 차이를 이해하고, 기업 환경에서 어떤 라이선스가 허용되는지 알아봅니다. 라이선스 위반 시 발생하는 법적 리스크를 사전에 예방하세요.",
    deadline: "2025-12-31",
    duration: "30분",
    courseUrl: "https://www.copyright.or.kr/education/educlass/learning/index.do",
    category: "required",
    thumbnailUrl: "",
    order: 0,
    visible: true,
    createdAt: now,
  },
  {
    id: "c_edu_002",
    title: "회사에서 개인 라이선스를 사용하면 안 되는 이유",
    description: "Adobe, Microsoft, Autodesk 등 주요 SW 벤더는 개인용(Personal) 라이선스의 기업 사용을 명시적으로 금지합니다. 실제 감사 적발 사례와 수천만 원의 합의금 사례를 통해 위험성을 확인하세요.",
    deadline: "2025-12-31",
    duration: "25분",
    courseUrl: "https://www.bsa.org/ko/resources/reports",
    category: "required",
    thumbnailUrl: "",
    order: 1,
    visible: true,
    createdAt: now,
  },
  {
    id: "c_edu_003",
    title: "크랙·불법 소프트웨어 사용 금지 및 처벌 기준",
    description: "저작권법 제136조: 영리 목적 저작권 침해 → 5년 이하 징역 또는 5,000만 원 이하 벌금. 크랙 SW는 악성코드 감염 경로이기도 합니다. 2023년 국내 적발 기업 사례와 실제 벌금액을 다룹니다.",
    deadline: "2025-12-31",
    duration: "40분",
    courseUrl: "https://www.law.go.kr/lsInfoP.do?lsiSeq=222614",
    category: "policy",
    thumbnailUrl: "",
    order: 2,
    visible: true,
    createdAt: now,
  },
  {
    id: "c_edu_004",
    title: "불법 소프트웨어 사용 적발 실사례",
    description: "BSA(Business Software Alliance) 신고·감사 프로세스, 국내 주요 기업 적발 사례 5건. 평균 합의금 3,000만~2억 원. 실제 공문 양식 및 대응 절차를 안내합니다.",
    deadline: "2025-12-31",
    duration: "35분",
    courseUrl: "https://www.bsa.org/ko/resources/reports/software-asset-management",
    category: "policy",
    thumbnailUrl: "",
    order: 3,
    visible: true,
    createdAt: now,
  },
  {
    id: "c_edu_005",
    title: "오픈소스 라이선스 올바른 사용법 (GPL·MIT·Apache)",
    description: "GPL은 소스코드 공개 의무가 있어 기업 내부 제품에 무단 사용 시 법적 문제가 됩니다. MIT·Apache 2.0은 상업적 사용 가능. 라이선스별 조건과 기업 사용 허가 범위를 정리합니다.",
    deadline: "2025-12-31",
    duration: "30분",
    courseUrl: "https://olis.or.kr/license/licenseGuide.do",
    category: "material",
    thumbnailUrl: "",
    order: 4,
    visible: true,
    createdAt: now,
  },
];

// ─── 자료실 (Resources) ─────────────────────────────────────────────────────
// 기업에서 무료로 사용 가능한 SW 설치 링크 모음
const RESOURCES = [
  {
    id: "r_res_001",
    title: "LibreOffice 7.6 — MS Office 대체 오피스 스위트",
    category: "install",
    fileUrl: "https://www.libreoffice.org/download/download/",
    fileType: "LINK",
    fileSize: "약 340MB",
    description: "Writer(문서)·Calc(스프레드시트)·Impress(프레젠테이션) 포함. Apache/LGPL 라이선스, 기업 무료 사용 가능.",
    updatedAt: today,
    order: 0,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_002",
    title: "7-Zip — 파일 압축·해제 프로그램",
    category: "install",
    fileUrl: "https://www.7-zip.org/download.html",
    fileType: "LINK",
    fileSize: "약 1.5MB",
    description: "WinRAR·WinZip 상업 라이선스 없이 사용할 수 있는 무료 압축 프로그램. LGPL 라이선스, 기업 무료 사용 가능.",
    updatedAt: today,
    order: 1,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_003",
    title: "VS Code — 코드·텍스트 편집기",
    category: "install",
    fileUrl: "https://code.visualstudio.com/download",
    fileType: "LINK",
    fileSize: "약 90MB",
    description: "Microsoft 제공. 메모장·Notepad++ 대체로 가볍고 강력한 편집기. MIT 라이선스, 기업 무료 사용 가능.",
    updatedAt: today,
    order: 2,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_004",
    title: "VLC Media Player — 동영상·음악 재생기",
    category: "install",
    fileUrl: "https://www.videolan.org/vlc/",
    fileType: "LINK",
    fileSize: "약 40MB",
    description: "대부분의 미디어 포맷 재생 지원. GPL 라이선스, 기업 무료 사용 가능. 곰플레이어·KMPlayer 대체.",
    updatedAt: today,
    order: 3,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_005",
    title: "GIMP — 이미지 편집 프로그램",
    category: "install",
    fileUrl: "https://www.gimp.org/downloads/",
    fileType: "LINK",
    fileSize: "약 250MB",
    description: "Adobe Photoshop 대체. 사진 편집·합성·리사이즈 등 지원. GPL 라이선스, 기업 무료 사용 가능.",
    updatedAt: today,
    order: 4,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_006",
    title: "PDF24 Creator — PDF 생성·변환·병합 도구",
    category: "install",
    fileUrl: "https://www.pdf24.org/ko/creator.html",
    fileType: "LINK",
    fileSize: "약 40MB",
    description: "PDF 생성·병합·분리·압축·변환 등 전 기능 무료. 기업 무료 사용 가능. Adobe Acrobat Pro 부분 대체.",
    updatedAt: today,
    order: 5,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_007",
    title: "Inkscape — 벡터 이미지 편집기",
    category: "install",
    fileUrl: "https://inkscape.org/release/",
    fileType: "LINK",
    fileSize: "약 110MB",
    description: "Adobe Illustrator 대체. SVG 기반 벡터 디자인 툴. GPL 라이선스, 기업 무료 사용 가능.",
    updatedAt: today,
    order: 6,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_008",
    title: "Mozilla Thunderbird — 이메일 클라이언트",
    category: "install",
    fileUrl: "https://www.thunderbird.net/ko/",
    fileType: "LINK",
    fileSize: "약 90MB",
    description: "Outlook 대체 가능한 무료 이메일 클라이언트. Mozilla Public License, 기업 무료 사용 가능.",
    updatedAt: today,
    order: 7,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_009",
    title: "[정책] SW 라이선스 관리 지침 및 준수사항",
    category: "policy",
    fileUrl: "#",
    fileType: "PDF",
    fileSize: "내부 문서",
    description: "회사 내 소프트웨어 라이선스 관리 정책, 구매 절차, 불법 SW 신고 방법, 위반 시 제재 규정을 안내합니다.",
    updatedAt: today,
    order: 8,
    visible: true,
    createdAt: now,
  },
  {
    id: "r_res_010",
    title: "[정책] 개인정보 및 보안 SW 설치 금지 목록",
    category: "policy",
    fileUrl: "#",
    fileType: "PDF",
    fileSize: "내부 문서",
    description: "보안 위협 또는 정보 유출 우려로 설치가 금지된 소프트웨어 목록과 이유, 대체 SW를 안내합니다.",
    updatedAt: today,
    order: 9,
    visible: true,
    createdAt: now,
  },
];

// ─── SW 검색 화이트/블랙리스트 (SwItem) ────────────────────────────────────
const SW_ITEMS = [
  // ── 화이트리스트 (approved) ─────────────────────────
  {
    id: "sw_white_001",
    name: "LibreOffice",
    vendor: "The Document Foundation",
    category: "오피스",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "MS Office 대체 오피스 스위트. Apache/LGPL 라이선스로 기업 무료 사용 가능. Writer·Calc·Impress·Draw 포함.",
    officialUrl: "https://www.libreoffice.org",
    resourceId: "r_res_001",
  },
  {
    id: "sw_white_002",
    name: "7-Zip",
    vendor: "Igor Pavlov",
    category: "압축",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "LGPL 라이선스 압축 프로그램. WinRAR·WinZip의 무료 대체재. ZIP·7Z·RAR 등 대부분의 압축 포맷 지원.",
    officialUrl: "https://www.7-zip.org",
    resourceId: "r_res_002",
  },
  {
    id: "sw_white_003",
    name: "Visual Studio Code",
    vendor: "Microsoft",
    category: "개발도구",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "MIT 라이선스. 무료 코드·텍스트 편집기. 다양한 확장(Extension) 지원. 개발자·기획자 모두 사용 가능.",
    officialUrl: "https://code.visualstudio.com",
    resourceId: "r_res_003",
  },
  {
    id: "sw_white_004",
    name: "VLC Media Player",
    vendor: "VideoLAN",
    category: "미디어",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "GPL 라이선스 미디어 플레이어. MP4·MKV·AVI 등 거의 모든 포맷 재생. 곰플레이어·KMPlayer 안전 대체재.",
    officialUrl: "https://www.videolan.org/vlc/",
    resourceId: "r_res_004",
  },
  {
    id: "sw_white_005",
    name: "GIMP",
    vendor: "GNOME / 오픈소스 커뮤니티",
    category: "이미지 편집",
    status: "approved",
    alternatives: ["Photoshop"],
    mandatory: false,
    description: "GPL 라이선스. 사진 편집·합성·색보정 기능 제공. Adobe Photoshop 구매 전 업무용 대체재로 활용 가능.",
    officialUrl: "https://www.gimp.org",
    resourceId: "r_res_005",
  },
  {
    id: "sw_white_006",
    name: "PDF24 Creator",
    vendor: "Geek Software GmbH",
    category: "PDF 도구",
    status: "approved",
    alternatives: ["Adobe Acrobat Pro"],
    mandatory: false,
    description: "기업 무료 사용 가능. PDF 생성·병합·분리·압축·OCR 등 지원. Adobe Acrobat Pro의 핵심 기능 대체.",
    officialUrl: "https://www.pdf24.org",
    resourceId: "r_res_006",
  },
  {
    id: "sw_white_007",
    name: "Mozilla Firefox",
    vendor: "Mozilla Foundation",
    category: "웹브라우저",
    status: "approved",
    alternatives: [],
    mandatory: false,
    description: "Mozilla Public License. 기업 무료 사용 가능. 개인정보 보호 기능 강화, 기업용 정책 설정(GPO) 지원.",
    officialUrl: "https://www.mozilla.org/ko/firefox/",
    resourceId: "",
  },
  {
    id: "sw_white_008",
    name: "Inkscape",
    vendor: "Inkscape 오픈소스 커뮤니티",
    category: "디자인",
    status: "approved",
    alternatives: ["Adobe Illustrator"],
    mandatory: false,
    description: "GPL 라이선스. SVG 기반 벡터 이미지 편집. 로고·아이콘·일러스트 제작. Adobe Illustrator 대체.",
    officialUrl: "https://inkscape.org",
    resourceId: "r_res_007",
  },

  // ── 블랙리스트 (banned) ─────────────────────────────
  {
    id: "sw_black_001",
    name: "uTorrent (μTorrent)",
    vendor: "BitTorrent Inc.",
    category: "P2P",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "⛔ P2P 프로그램. 불법 콘텐츠 다운로드 통로로 악용되며, 번들 애드웨어·악성코드 배포 이력 다수. 사내망 보안 정책 위반.",
    officialUrl: "",
    resourceId: "",
  },
  {
    id: "sw_black_002",
    name: "WinRAR (미인증 사용)",
    vendor: "RARLAB",
    category: "압축",
    status: "banned",
    alternatives: ["7-Zip"],
    mandatory: false,
    description: "⛔ 셰어웨어(Shareware). 40일 무료 평가판 이후에도 계속 사용 시 상업 라이선스 필요. 기업 미인증 사용은 저작권 위반. 대체: 7-Zip (무료).",
    officialUrl: "",
    resourceId: "r_res_002",
  },
  {
    id: "sw_black_003",
    name: "TeamViewer (개인 무료 버전 업무 사용)",
    vendor: "TeamViewer AG",
    category: "원격제어",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "⛔ 개인 무료(Free) 버전의 상업적·업무 사용 금지. TeamViewer는 상업적 사용 감지 시 원격 연결을 자동 차단하고 라이선스 구매를 요구함.",
    officialUrl: "",
    resourceId: "",
  },
  {
    id: "sw_black_004",
    name: "KMPlayer (2.x 구버전)",
    vendor: "PandoraTV",
    category: "미디어",
    status: "banned",
    alternatives: ["VLC Media Player"],
    mandatory: false,
    description: "⛔ 구버전(2.x) 악성코드 배포 이력. 사용자 정보 무단 수집 이슈. 업무용 PC 설치 금지. 대체: VLC Media Player.",
    officialUrl: "",
    resourceId: "r_res_004",
  },
  {
    id: "sw_black_005",
    name: "Adobe Acrobat (크랙·비인증)",
    vendor: "Adobe Inc.",
    category: "PDF 도구",
    status: "banned",
    alternatives: ["PDF24 Creator"],
    mandatory: false,
    description: "⛔ 불법 소프트웨어 사용의 가장 빈번한 사례. BSA 신고 1위 품목. 크랙 설치 파일에 악성코드 포함 위험 높음. 대체: PDF24 Creator.",
    officialUrl: "",
    resourceId: "r_res_006",
  },
  {
    id: "sw_black_006",
    name: "Internet Download Manager (IDM) 크랙",
    vendor: "Tonec Inc.",
    category: "다운로드",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "⛔ 셰어웨어. 크랙 버전 유통이 광범위하며 악성코드 감염 경로. 정품 라이선스 없이 사용 시 저작권법 위반.",
    officialUrl: "",
    resourceId: "",
  },
  {
    id: "sw_black_007",
    name: "CCleaner Free (구버전)",
    vendor: "Piriform (Avast)",
    category: "시스템 최적화",
    status: "banned",
    alternatives: [],
    mandatory: false,
    description: "⛔ 2017년 공식 배포 버전에 악성코드(Floxif) 삽입 사건 발생. 이후 보안 신뢰도 하락. 업무용 PC 사용 자제 권고.",
    officialUrl: "",
    resourceId: "",
  },
];

// ─── 실행 ────────────────────────────────────────────────────────────────────
async function seed() {
  const client = new Redis(REDIS_URL, { maxRetriesPerRequest: 1 });

  try {
    console.log("🌱 Redis 연결 중...");

    await client.set("portal:courses",   JSON.stringify(COURSES));
    console.log(`✅ 교육센터 ${COURSES.length}건 등록`);

    await client.set("portal:resources", JSON.stringify(RESOURCES));
    console.log(`✅ 자료실 ${RESOURCES.length}건 등록`);

    await client.set("portal:swdb",      JSON.stringify(SW_ITEMS));
    console.log(`✅ SW 화이트/블랙리스트 ${SW_ITEMS.length}건 등록`);

    console.log("\n🎉 시드 완료! https://swportal.vercel.app 에서 확인하세요.");
  } finally {
    await client.quit();
  }
}

seed().catch(e => { console.error("❌ 오류:", e); process.exit(1); });
