name: Deploy to Vercel (Production)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_miijipnkRmR5TQrKJQU4ty2s
          VERCEL_PROJECT_ID: prj_tJwlIHXYeRcHJa99XqkAUnszUMoX
